### ISSUE TITLE
NOT IN BUG

### ISSUE THREAD

**Issue by StevenWi87** [demmings/gsSQL#48]
NOT IN BUG PLEASE HELP FIX IT 

![image](https://github.com/demmings/gsSQL/assets/103827902/5545f9bd-90d5-4495-939e-aa46b47187e2)

**Comment by demmings** [comment]
StevenWi87,
Try using only one set of brackets around your list of subjects.  Example from my TDD worksheet:
**=gsSQL("SELECT * FROM editors WHERE first_name IN (' Mark ', 'Maria    ', 'CATHRINE  ', '  jacK') ")**

**Comment by StevenWi87** [comment]
thanks for reply IN is work but not with NOT IN 

![image](https://github.com/demmings/gsSQL/assets/103827902/38e1d87a-2fac-4308-8e33-760541e0518b)

**Comment by demmings** [comment]
StevenWi87,

Two separate fixes for this.

1.  A fixed list of items (not a sub-query) would only process the first item in the list.  All items after the first were ignored.
2. A fixed list of ONE item would cause an error.

Known Possible differences from MySql implentation.
gsSQL() where IN or NOT IN is CASE SENSITIVE, where the default behavior in my local linux is case insensitive.  From my reading on this subject however, it depends how the database was setup - so I am going to leave this case sensitivity as is.

You need to copy the lastest distribution.
https://github.com/demmings/gsSQL/blob/main/dist/gssql.js

**Comment by StevenWi87** [comment]
already fix 

but have another problem now 

![image](https://github.com/demmings/gsSQL/assets/103827902/0a95a13a-e92a-46c7-b1fd-f5e8a050e27d)

compare with this one

**Comment by StevenWi87** [comment]
![image](https://github.com/demmings/gsSQL/assets/103827902/7569d03d-3a3e-4e51-a181-db6f115c6125)

**Comment by demmings** [comment]
StevenWi87,
I re-ran the setup for my TDD sheet.  Looking at test #27, it appears to be correct at this time.
The failure of some tests are not critical on that page.  Some things like how dates are represented inside Javascript (for my NODE testing) don't match up exactly to sheets dates - so it fails.  There are also formatting issues that sheets will format dates/numbers differently - so it fails.    Test #35 has a problem, but it something to do with passing in a Javascript date into the bind variable and something messes up on my test sheet - but I am not concerned for now.  right now I have a script that tries to generate my sheet data tests from all of my internal testing - and it is not perfect.

**Comment by StevenWi87** [comment]
thanks
