### ISSUE TITLE
library id not working 

### ISSUE THREAD

**Issue by StevenWi87** [demmings/gsSQL#52]
1ZfedAgGG2K5kPLC2NPfe0Kb1xAg-0gvmliR3V8pRNk6DZMTUQyCbMW1W
 
 not working 
 
 
![image](https://github.com/demmings/gsSQL/assets/103827902/8d6d3676-c3f8-467f-827b-1c66cbba51c6)

**Comment by demmings** [comment]
I modified the rights to the project - so hopefully that does it.  When I tried using on a new sheet, I was using the same Google Account, so I did not see this problem.
