### ISSUE TITLE
Error when CONCAT_WS() receives MONTH() as param

### ISSUE THREAD

**Issue by Juan-Allegretti** [demmings/gsSQL#57]
I attempted to execute the following statement:
`SELECT CONCAT_WS('/', DAY(MYTABLE.MYDATE), MONTH(MYTABLE.MYDATE), YEAR(MYTABLE.MYDATE)) AS 'MY_DATE_STRING' FROM MYTABLE
`
For instance, for the date 23/09/2023, I obtained the following result: 23/**81**/2023. This occurs because the [month()](https://github.com/demmings/gsSQL/blob/bd043403e480088cc81287773e32d9d186f7bf9b/dist/gssql.js#L3536) function returns `new Date(${parms[0]}).getMonth() + 1`

It can be fixed as follows:

```
month(parms){
    this.referencedTableColumns.push(parms[0]);
    return `(new Date(${parms[0]}).getMonth() + 1)`;
}
```

**Comment by demmings** [comment]
I wonder why DAY() and YEAR() don't bug out the same way.  I will check up on this soon.  Thanks for your help.

**Comment by demmings** [comment]
Suggested change implemented and works as expected.
